/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Arbait;

import org.example.Gui.Arbait.Model.ModelAllNastil;
import org.example.Gui.Form.Helps.FGetDate;
import org.example.Gui.THaupt;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.example.logic.ZadachaNastil;
import org.example.util.DateRenderer;
import org.example.util.HelpClass;
import org.example.util.IOOperator;
import org.example.util.IOZadachaNastil;

/**
 *
 * @author ivan
 */
public class LAllNastil extends javax.swing.JPanel {

    /**
     * Creates new form LAllNastil
     * @param th1
     */
    public LAllNastil(THaupt th1) {
        initComponents();
        th = th1;
        jButton5.setVisible(false);
        jButton3.setVisible(false);
        jButton4.setVisible(false);
        jLabel1.setText("");
        Calendar c = Calendar.getInstance();
        c.add(Calendar.DAY_OF_MONTH, 10);
        d2 = c.getTime();
        c.add(Calendar.DAY_OF_MONTH, -17);
        d1 = c.getTime();
    }
    
    Date d1, d2;    
    THaupt th;
    ModelAllNastil model = new ModelAllNastil();
    TableRowSorter<TableModel> sorter;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/cancel.png"))); // NOI18N
        jButton1.setText("Закрыть");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/edit.png"))); // NOI18N
        jButton2.setText("Изменить");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/bac.png"))); // NOI18N
        jButton5.setText("Возвраты");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/2.png"))); // NOI18N
        jButton3.setText("Утвердить");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/1.png"))); // NOI18N
        jButton4.setText("Открыть");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/refresh.png"))); // NOI18N
        jButton6.setText("Обновить");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/filter.png"))); // NOI18N
        jButton7.setText("Фильтр");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jCheckBox1.setText("Закрытые");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jCheckBox1);

        jLabel1.setText("jLabel1");
        jToolBar1.add(jLabel1);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        // TODO add your handling code here:
        if(jTable1.getColumnCount()<=0)
            return;
        int h = (jTable1.getWidth()-400)/6;
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);  
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(h);  
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(h);  
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(h);  
        
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);          
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(h);  
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(100);  
        
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(h);  
        
        
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(70);  
        jTable1.getColumnModel().getColumn(11).setPreferredWidth(h);  
        jTable1.getColumnModel().getColumn(12).setPreferredWidth(100);  
        
        jTable1.getColumnModel().getColumn(13).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(13).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(13).setMinWidth(0);
    }//GEN-LAST:event_jTable1ComponentResized

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if(IOOperator.getSetupOperator(19)>1)
        {
            jButton3.setVisible(true);
            jButton4.setVisible(true);
        }
        model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);
        jTable1.setModel(model);
        jTable1.setShowGrid(true);                    
        jTable1.getTableHeader().setReorderingAllowed(false);   
        jTable1.getColumnModel().getColumn(1).setCellRenderer(model.jTableRenderer);
        jTable1.getColumnModel().getColumn(5).setCellRenderer(HelpClass.jTableRendererColumnRight);
        jTable1.getColumnModel().getColumn(9).setCellRenderer(HelpClass.jTableRendererColumnRight);
        jTable1.getColumnModel().getColumn(10).setCellRenderer(HelpClass.jTableRendererColumnRight);
        jTable1.getColumnModel().getColumn(12).setCellRenderer(new DateRenderer());
        jTable1ComponentResized(null);
        
        TimerTask tt = new TimerTask() {
            @Override
            public void run() {                         
                int h = jTable1.getSelectedRow();
                model.setData(1,jCheckBox1.isSelected()?4:3,0);
                if (h != -1) {
                    try {
                        jTable1.setRowSelectionInterval(h, h);
                    } catch (IllegalArgumentException e) {
                    }

                }
            }
        };
        Timer tm = new Timer();                       
        tm.schedule(tt, 600000, 600000); 
        sorter = new TableRowSorter<TableModel>(model);        
        jTable1.setRowSorter(sorter);        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        th.closeTabPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        FNastil fn = new FNastil(null, true, (int)jTable1.getValueAt(h, 0));
        fn.setVisible(true);
        model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);
        if(jTable1.getRowCount()>0)
            jTable1.setRowSelectionInterval(h, h);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        if (JOptionPane.showConfirmDialog(null, "Вы действительно хотите утвердить настил <" + jTable1.getValueAt(jTable1.getSelectedRow(), 3) + ">?", "Вопрос.", JOptionPane.YES_NO_OPTION) == 0) {
            /*if (!IOZadachaNastil.executeNastilForQty((int)jTable1.getValueAt(h, 0))) {
                JOptionPane.showMessageDialog(null, "Общий вес настила не соответствует сумме итоговых весов!");                
                return;
            }*/
            
           /* if (!IOZadachaNastil.executeNastilForQtyReturn((int)jTable1.getValueAt(h, 0))) {
                JOptionPane.showMessageDialog(null, "Общий вес возвращаемых полотен не соответствует введенному весу для возврата!");                
                return;
            }*/
            
            ZadachaNastil zn =  IOZadachaNastil.getListZadachaNastil(0, (int)jTable1.getValueAt(h, 0)).get(0);
            
            
            if(zn.getQtyl()==0)
            {
                JOptionPane.showMessageDialog(null, "Введите количество слоев!");
                return;
            }
            
            if(     !HelpClass.checkNotEdit(zn.getQtyaddarticle()) ||
                    !HelpClass.checkNotEdit(zn.getQtydel()) ||
                    !HelpClass.checkNotEdit(zn.getQtydel1()) ||
                    !HelpClass.checkNotEdit(zn.getQtyend()) ||
                    !HelpClass.checkNotEdit(zn.getQtygut()) ||
                    !HelpClass.checkNotEdit(zn.getQtylosk()) ||
                    !HelpClass.checkNotEdit(zn.getQtylosk1()) ||
                    !HelpClass.checkNotEdit(zn.getQtytruba()) ||
                    !HelpClass.checkNotEdit(zn.getQtyreturn()) ||
                    !HelpClass.checkNotEdit(zn.getQtybeika())){
                JOptionPane.showMessageDialog(null, "Введите правильный вес!");
                return;
            }
            
            
            
            int r;
            if(zn.getQtyreturn().signum()==0)        
                r = IOZadachaNastil.setStatusOkForNastil(zn.getZadachanastil(), 3);
            else
                r = IOZadachaNastil.setStatusOkForNastil(zn.getZadachanastil(), 2);
            
            //int r = IOZadachaNastil.setStatusOkForNastil((int)jTable1.getValueAt(h, 0), 2);
            if(r==0)
            {
                model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);
                if(jTable1.getRowCount()>0)
                    jTable1.setRowSelectionInterval(h, h);
                
            }
            else
                JOptionPane.showMessageDialog(null, "Ошибка утверждения. ");
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        FReturn fr = new FReturn(null, true, (int)jTable1.getValueAt(h, 0));
        fr.setVisible(true);
        model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * отменим отработку настила
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        if (JOptionPane.showConfirmDialog(null, "Вы действительно хотите открыть для редактирования настил <" + jTable1.getValueAt(jTable1.getSelectedRow(), 3) + ">?", "Вопрос.", JOptionPane.YES_NO_OPTION) == 0) 
        {                        
            int r = IOZadachaNastil.setStatusEditForNastil((int)jTable1.getValueAt(h, 0), 1);
            if(r>=0)
            {
                model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);
                if(jTable1.getRowCount()>0)
                    jTable1.setRowSelectionInterval(h, h);
            }
            else
            {
                if(r==-1)
                    JOptionPane.showMessageDialog(null, "Настил закрыт для редактирования. Его нельзя открыть!");
                if(r==-2)
                    JOptionPane.showMessageDialog(null, "Задача закрыта для редактирования!");
                if(r==-3)
                    JOptionPane.showMessageDialog(null, "Настил нельзя редактировать! Возвращаемые полотна уже используются!");
                if(r==-4)
                    JOptionPane.showMessageDialog(null, "Настил нельзя редактировать! Лоскуты уже используются!");
            }
        }   
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:        
        model.setData(1,jCheckBox1.isSelected()?4:3,0, d1, d2);        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode())
        {
            // удалить значение
            
            case KeyEvent.VK_ESCAPE:
            {
                jLabel1.setText("");                
                setFilter();
                break;
            }                  
            case KeyEvent.VK_BACK_SPACE:
            {
                jLabel1.setText(jLabel1.getText().substring(0, (jLabel1.getText().length()-1)>0?(jLabel1.getText().length()-1):0));                
                setFilter();
                break;
            }            
            default:
                //if(String.valueOf(evt.getKeyChar()).matches("[0-9а-яА-Яa-zA-Z-\\s\\w]"))                
                if(String.valueOf(evt.getKeyChar()).matches("[A-Za-zА-Яа-я0-9/]"))                
                {
                    jLabel1.setText(jLabel1.getText()+evt.getKeyChar());
                    setFilter();                    
                }                 
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //Calendar c = Calendar.getInstance();
        //c.add(Calendar.DAY_OF_MONTH, -10);
        FGetDate fg = new FGetDate(null, true, d1, d2);
        fg.setVisible(true);
        if(fg.getResult())
        {
            d1 = fg.getDate1();
            d2 = fg.getDate2();
            model.setData(1,jCheckBox1.isSelected()?4:3, 0, d1, d2);                    
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void setFilter()
    {
        sorter.setRowFilter(RowFilter.regexFilter("(?iu)"+jLabel1.getText(), 3));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
