/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Arbait;

import org.example.Gui.Arbait.Model.ModelZadacha;
import org.example.Gui.Form.Helps.FGetDate;
import org.example.Gui.THaupt;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import org.example.logic.Zadacha;
import org.example.logic.ZadachaPrintDetali;
import org.example.util.IOOperator;
import org.example.util.IOZadacha;
import org.example.util.IOZadachaKomplektovka;
import org.example.util.IOZadachaPrintDetali;

/**
 *
 * @author ivan
 */
public class LZadachaEndArbait extends javax.swing.JPanel {

    /**
     * Creates new form LZadachaAllNastil
     * @param th1
     */
    public LZadachaEndArbait(THaupt th1) {
        initComponents();
        th = th1;
        jButton6.setVisible(false);
        jButton7.setVisible(false);
        jButton2.setVisible(false);
        
        jButton3.setVisible(false);        
        jButton4.setVisible(false);
        Calendar c = Calendar.getInstance();
        c.add(Calendar.DAY_OF_MONTH, 10);
        d2 = c.getTime();
        c.add(Calendar.DAY_OF_MONTH, -90);
        d1 = c.getTime();
    }

    THaupt th;
    ModelZadacha model = new ModelZadacha(2);
    Date d1, d2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/cancel.png"))); // NOI18N
        jButton1.setText("Выход");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/cascade.png"))); // NOI18N
        jButton2.setText("Настилы");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/basket.png"))); // NOI18N
        jButton6.setText("Фурнитура");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/document.png"))); // NOI18N
        jButton7.setText("Комплектовка");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/2.png"))); // NOI18N
        jButton3.setText("Закрыть задачу");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/1.png"))); // NOI18N
        jButton4.setText("Открыть");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/refresh.png"))); // NOI18N
        jButton5.setText("Обновить");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/filter.png"))); // NOI18N
        jButton8.setText("Фильтр");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setRowHeight(26);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        th.closeTabPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        // TODO add your handling code here:
        if(jTable1.getColumnCount()<=0)
            return;
       
        int h = (jTable1.getWidth()-310)/4;
        
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(h);  
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);  
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(h);  
        
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(h);  
        
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(120);  
        jTable1.getColumnModel().getColumn(6).setPreferredWidth(80);  
        jTable1.getColumnModel().getColumn(7).setPreferredWidth(80);  
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(h);  
        
        jTable1.getColumnModel().getColumn(9).setPreferredWidth(0);
        jTable1.getColumnModel().getColumn(9).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(9).setMinWidth(0);
        
        jTable1.getColumnModel().getColumn(10).setPreferredWidth(30);  
    }//GEN-LAST:event_jTable1ComponentResized

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if(IOOperator.getSetupOperator(41)>1)
        {
            jButton3.setVisible(true);
            jButton4.setVisible(true);
        }
        model.setData(d1, d2, -1);
        jTable1.setModel(model);
        jTable1.setShowGrid(true);                    
        jTable1.getTableHeader().setReorderingAllowed(false);   
        jTable1.getColumnModel().getColumn(1).setCellRenderer(jTableRenderer);
        jTable1.getColumnModel().getColumn(10).setCellRenderer(model.jTableRendererHand);
        jTable1ComponentResized(null);
    }//GEN-LAST:event_formComponentShown

    
    // подсветка и картинки в таблицу                       
    final ImageIcon edit = new ImageIcon(getClass().getResource("/org/example/images/1.png"));
    final ImageIcon ok1 = new ImageIcon(getClass().getResource("/org/example/images/2.png"));
    final ImageIcon ok2 = new ImageIcon(getClass().getResource("/org/example/images/up.png"));
    final ImageIcon ok3 = new ImageIcon(getClass().getResource("/org/example/images/cascade.png"));
    final ImageIcon ok10 = new ImageIcon(getClass().getResource("/org/example/images/clos.png"));
    public DefaultTableCellRenderer jTableRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            //if (vid == 1) {
            int v = Integer.parseInt(cell.getText()) ;
                if (column == 1) {
                    switch (v) {
                        case 0:
                            cell.setIcon(edit);
                            cell.setText("");
                            break;
                        case 1:
                            cell.setIcon(edit);
                            cell.setText("");
                            break;
                        case 2:
                            cell.setIcon(edit);
                            cell.setText("");
                            break;
                        case 3:
                            cell.setIcon(ok3);
                            cell.setText("");
                            break;
                        case 10:
                            cell.setIcon(ok10);
                            cell.setText("");
                            break;    
                    }
                }
            return cell;
        }

    };
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1)
            return;
        LZadachaNastil lz = new LZadachaNastil(null, true, (int)jTable1.getValueAt(h, 0));
        lz.setSize(getWidth()-50, getHeight()+150);
        lz.setVisible(true);
        model.setData(d1, d2, -1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        model.setData(d1, d2, -1);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * Утвердить
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1)
            return;
        //h = (int) jTable1.getValueAt(h, 0);
        if (JOptionPane.showConfirmDialog(null, "Вы действительно хотите закрыть задание <" + jTable1.getValueAt(jTable1.getSelectedRow(), 2) + ">?", "Вопрос.", JOptionPane.YES_NO_OPTION) == 0) 
        {
            Zadacha zz = IOZadacha.getListZadacha((int)jTable1.getValueAt(h, 0), 0).get(0);
            
            if(zz.getStatus()>3)
            {
                JOptionPane.showMessageDialog(null, "Задание уже утверждено!");
                return;
            }
            
            if(zz.getStatus()<2)
            {
                JOptionPane.showMessageDialog(null, "Задание еще в стадии редактирования!");
                return;
            }
            
            // проверим все или нет закрыты настилы
            int r =IOZadacha.getCloseZadacha((int)jTable1.getValueAt(h, 0));
            if(r<0)
            {
                if(r==-1)
                {
                    JOptionPane.showMessageDialog(null, "В заданий есть не отработанные настилы!");
                    return;
                }
                
                if(r==-2)
                {
                    JOptionPane.showMessageDialog(null, "В заданий есть не отработанные полотна!");
                    return;
                }
            } 
            
            // проверим набрана ли фурнитура
            // проверим нужна ли фурнитура для модели
            /*if(!IOModel.getListModelProduct(zz.getModel().getModel(), -1 , 2).isEmpty())
            {
                if(IOZadachaFurnitura.getListZadachaFurnitura(zz.getZadacha(), -1).isEmpty())
                {
                    JOptionPane.showMessageDialog(null, "Для задачи не набрана фурнитура!");
                    return;
                }
            }*/
            
            // посмотрим все ли маршруты вернулмсь
            if(!IOZadachaKomplektovka.getListZadachaKomplektovkaIsNotGut(zz.getZadacha()).isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Не все маршруты выполнены!");
                return;
            }

            // посмотрим все или нет закрыты принты и вышивки
            List<ZadachaPrintDetali> ls = IOZadachaPrintDetali.getListZadachaPrintDetaliForZadacha(zz.getZadacha());
            if(!ls.isEmpty())
            {
               for(ZadachaPrintDetali z: ls)
               {
                   if(z.getStatus()!=1)
                   {
                       JOptionPane.showMessageDialog(null, "Не все детали с вышивкой/принтом отработаны!");
                       return;
                   }
               }
               // Изменим статус на закрытый
               for(ZadachaPrintDetali z: ls)               
                   IOZadachaPrintDetali.updateStatusPD(z.getZadachaprintdetali(), 2);
               
               
            }
                        
            if(IOZadacha.setNewStatusZadacha((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0), 10))
            {
                model.setData(d1, d2, -1);
                jTable1.setRowSelectionInterval(h, h);
            }
            else
                JOptionPane.showMessageDialog(null, "Ошибка закрытия");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1)
            return;
        //h = (int) jTable1.getValueAt(h, 0);
        if (JOptionPane.showConfirmDialog(null, "Вы действительно хотите открыть задание <" + jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "> для формирования настилов?", "Вопрос.", JOptionPane.YES_NO_OPTION) == 0) 
        {
            Zadacha zz = IOZadacha.getListZadacha((int)jTable1.getValueAt(h, 0), 0).get(0);
            
            /*if(zz.getStatus()>3)
            {
                JOptionPane.showMessageDialog(null, "Нельзя открыть задание!");
                return;
            }*/
            
            if(zz.getStatus()<=3)
            {
                //JOptionPane.showMessageDialog(null, "Задание еще в стадии редактирования!");
                return;
            }
            
            // посмотрим все или нет закрыты принты и вышивки
            List<ZadachaPrintDetali> ls = IOZadachaPrintDetali.getListZadachaPrintDetaliForZadacha(zz.getZadacha());
            // Изменим статус на закрытый
            for(ZadachaPrintDetali z: ls)               
                IOZadachaPrintDetali.updateStatusPD(z.getZadachaprintdetali(), 1);
                
            if(IOZadacha.setOldStatusZadacha((int)jTable1.getValueAt(jTable1.getSelectedRow(), 0), 3))
            {
                model.setData(d1, d2, -1);
                jTable1.setRowSelectionInterval(h, h);
            }
            else
                JOptionPane.showMessageDialog(null, "Ошибка открытия");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
            jButton2ActionPerformed(null);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * Отпуск фурнитуры
     * @param evt 
     */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1)
            return;
        Zadacha zz = IOZadacha.getListZadacha((int)jTable1.getValueAt(h, 0), 0).get(0);
        if(zz.getStatus()<2)
        {
            JOptionPane.showMessageDialog(null, "Задание еще в стадии редактирования! Нельзя набирать фурнитуру!");
            return;
        }            
        
        FZadachaFurnitura zf = new FZadachaFurnitura(null, true, (int)jTable1.getValueAt(h, 0));
        zf.setSize(getWidth()-50, getHeight());
        zf.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1)
            return;
        Zadacha zz = IOZadacha.getListZadacha((int)jTable1.getValueAt(h, 0), 0).get(0);
        if(zz.getStatus()<2)
        {
            JOptionPane.showMessageDialog(null, "Задание еще в стадии редактирования!");
            return;
        }
        FZadachaKomplektovka fk = new FZadachaKomplektovka(null, true, (int)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        fk.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        FGetDate fg = new FGetDate(null, true, d1, d2);
        fg.setVisible(true);
        if(fg.getResult())
        {
            d1 = fg.getDate1();
            d2 = fg.getDate2();
            model.setData(d1, d2, -1);
        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
