/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Analit;

import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author ivan
 */
public class FChart1 extends javax.swing.JDialog {

    /**
     * Creates new form FChart
     * @param parent
     * @param modal
     * @param ls1
     */
    public FChart1(java.awt.Frame parent, boolean modal, List<String> ls1, int w1, int h1, String tTitle1, boolean renameMont1) {
        super(parent, modal);
        initComponents();
        ls = ls1;
        w = w1;
        h = h1;
        tTitle = tTitle1;
        renameMont = renameMont1;
        
        //setContentPane(createDemoPanel());
        //getContentPane().add(createDemoPanel());
    }

    List<String> ls;
    String tTitle;
    int w,h;
    boolean renameMont = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("График");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setContentPane(createDemoPanel());
        repaint();
        setSize(w, h);
        //getContentPane().add(createDemoPanel());
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FChart1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                FChart1 dialog = new FChart1(new javax.swing.JFrame(), true, null, 0, 0, "", false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

    
    private JFreeChart createChart(CategoryDataset dataset) 
    {
        JFreeChart chart = ChartFactory.createBarChart(
                "Продажи за период",
                null, // x-axis label
                "Кол-во", // y-axis label
                dataset);
        chart.addSubtitle(new TextTitle(tTitle));
        chart.setBackgroundPaint(Color.white);

        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        
        
        
        CategoryAxis axis = plot.getDomainAxis();
        axis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
        

        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        chart.getLegend().setFrame(BlockBorder.NONE);

        return chart;
    }
    
    
    
private CategoryDataset createDataset()
{
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();
    //System.out.println("ZZZ= " + ls.size());
    String ss[];
    for(String s: ls)
    {
        ss = s.split("<!>");
        if(renameMont)
            dataset.addValue(Integer.parseInt(ss[0]), ss[1] , renameMontStr(ss[2]));
        else
            dataset.addValue(Integer.parseInt(ss[0]), ss[1] , ss[2]);
    }
    
    //dataset.addValue(52733, "Жена", "Январь");
    /*dataset.addValue(435, "Продажи" , "Январь");
    //dataset.addValue(51345, "Жена", "Февраль");
    dataset.addValue(896, "Продажи" , "Февраль");
    dataset.addValue(535, "Продажи" , "Март");
    dataset.addValue(635, "Продажи" , "Апрель");
    dataset.addValue(735, "Продажи1" , "Апрель");*/
    return dataset;
}
  

private String renameMontStr(String str)
{
    if(str.length()<6)
        return str;
    String s = str.substring(4,6);
    if(s.substring(0,1).equals("0"))
        s = s.substring(1,2);
    
    List<String> ls1 = new ArrayList<>();
    ls1.add("Январь");
    ls1.add("Февраль");
    ls1.add("Март");
    ls1.add("Апрель");
    ls1.add("Май");
    ls1.add("Июнь");
    ls1.add("Июль");
    ls1.add("Август");
    ls1.add("Сентябрь");
    ls1.add("Октябрь");
    ls1.add("Ноябрь");
    ls1.add("Декабрь");
    
    
    return str.substring(0,4) + " " + ls1.get(Integer.parseInt(s)-1);
}

    
public JPanel createDemoPanel()
{
    JFreeChart chart = createChart(createDataset());
    chart.setPadding(new RectangleInsets(4, 8, 2, 2));    
    
    
    ChartPanel panel = new ChartPanel(chart);
    panel.setFillZoomRectangle(true);
    panel.setMouseWheelEnabled(true);
    panel.setPreferredSize(new Dimension(600, 300));
       
    return panel;
}
    
    
/*private XYDataset createDataset()
{
    TimeSeries s1 = new TimeSeries("График продаж");
    SimpleDateFormat sd = new SimpleDateFormat("yyy-MM-dd");
    String ss[];
    
    for(String s: ls)
    {
        ss = s.split("#");
        try {
            s1.add(new Day(sd.parse(ss[0])), new BigDecimal(ss[1]));
        } catch (ParseException ex) {
            Logger.getLogger(FChart1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    TimeSeriesCollection dataset = new TimeSeriesCollection();
    dataset.addSeries(s1);
    //dataset.addSeries(s2);

    return dataset;
}

    
    private JFreeChart createChart(XYDataset dataset)
{
    JFreeChart chart = ChartFactory.createTimeSeriesChart(
        "График продаж",  // title
        "",                            // x-axis label
        "Кол-во",                      // y-axis label
        dataset,                       // data
        true,                          // create legend
        true,                          // generate tooltips
        false                          // generate URLs
    );

    chart.setBackgroundPaint(Color.white);
    
    XYPlot plot = (XYPlot) chart.getPlot();
    plot.setBackgroundPaint    (Color.lightGray);
    plot.setDomainGridlinePaint(Color.white    );
    plot.setRangeGridlinePaint (Color.white    );
    plot.setAxisOffset(new RectangleInsets(5.0, 5.0, 5.0, 5.0));
    plot.setDomainCrosshairVisible(true);
    plot.setRangeCrosshairVisible(true);

    XYItemRenderer r = plot.getRenderer();
    if (r instanceof XYLineAndShapeRenderer) {
        XYLineAndShapeRenderer renderer = (XYLineAndShapeRenderer) r;
        renderer.setBaseShapesVisible   (true);
        renderer.setBaseShapesFilled    (true);
        renderer.setDrawSeriesLineAsPath(true);
    }

    DateAxis axis = (DateAxis) plot.getDomainAxis();
    axis.setDateFormatOverride(new SimpleDateFormat("dd.MM.YYYY"));

    return chart;
}
    
    private JPanel createDemoPanel()
{
    JFreeChart chart = createChart(createDataset());
    chart.setPadding(new RectangleInsets(4, 8, 2, 2));
    ChartPanel panel = new ChartPanel(chart);
    panel.setFillZoomRectangle(true);
    panel.setMouseWheelEnabled(true);
    panel.setPreferredSize(new Dimension(600, 300));
    return panel;
}*/
    
}
