/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Analit;

import org.example.Gui.Form.Helps.FGetModel;
import org.example.Gui.Plan.LArticleInArbait;
import org.example.Gui.THaupt;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import org.example.logic.Color;
import org.example.logic.Model;
import org.example.logic.ModelProduct;
import org.example.logic.RabotnikGruppa;
import org.example.logic.Razmeri;
import org.example.logic.plan.PModelPlan;
import org.example.logic.plan.PModelPlanProduct;
import org.example.logic.plan.PModelPlanRazmeri;
import org.example.logic.plan.PModelYar;
import org.example.util.HelpClass;
import org.example.util.IOModel;
import org.example.util.analit.IOPrognoz;
import org.example.util.plan.IOModelPlan;
import org.example.util.plan.IOPModelYar;

/**
 *
 * @author ivan
 */  
public class FGetPrognoz2 extends javax.swing.JPanel {

    /**
     * Creates new form FGetPrognoz
     * @param th1
     */
    public FGetPrognoz2(THaupt th1) {
        initComponents();
        th = th1;
        jDateChooser1.setDate(new Date());
        jDateChooser2.setDate(new Date());
        
        jDateChooser2.setDate(new Date(new Long("1499451600000")));
        
        jDateChooser3.setDate(new Date(new Date().getTime() + Long.parseLong("15000000000")));
        
        //jDateChooser3.setVisible(false);
        jButton4.setVisible(false);
        
    }
    THaupt th;
    Model mod = new Model(199);
    ModelPrognoz1 model = new ModelPrognoz1();
    int yar;
    
    /**
     * Задать параметры
     * @param article - артикул
     * @param d1 - дата с
     * @param d2 - дата по
     * @param d3 - дата закупок
     * @param d4 - дата производства
     * @param d5 - дата начала продаж
     * @param ya
     */
    public void sendPadamert(int article, Date d1, Date d2, Date d3, Date d4, Date d5, int ya)
    {
        yar = ya;
        jTextField2.setText(String.valueOf(ya));
        //System.out.println("art = " + article);
        jDateChooser2.setDate(d1);
        jDateChooser1.setDate(d2);
        jDateChooser3.setDate(d3);
        jDateChooser4.setDate(d4);
        jDateChooser5.setDate(d5);
        mod = IOModel.getListModel(article, 0, true).get(0);
        jTextField1.setText(mod.getArticle());   
        jButton3ActionPerformed(null);
        
        System.out.println("art = " + article);
    }
    
    //ModelModelPlan  model3 = new ModelModelPlan();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/cancel.png"))); // NOI18N
        jButton1.setText("Закрыть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Дата С");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Дата По");

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Артикул");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Показать");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/example/images/add.png"))); // NOI18N
        jButton4.setText("Добавить цвет ");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Закупки");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Прозводство");

        jDateChooser4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Начало продаж");

        jDateChooser5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Добавить размер/цвет");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("История");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setText("Сформировать");
        jButton7.setToolTipText("Сформировать задаи для производства");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("В работе");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("2018");

        jButton9.setText("Добавить");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setText("График");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(13, 13, 13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton10))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)
                        .addComponent(jButton8)
                        .addComponent(jButton9)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(26);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        th.closeTabPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //model.setData();
        //jTable1.setModel(model);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        
        jTable1.setShowGrid(true);                    
        jTable1.getTableHeader().setReorderingAllowed(false);  
        
        
        jTable1.getTableHeader().setPreferredSize(new Dimension(22000, 80));
        
        /*jTable3.setShowGrid(true);                    
        jTable3.getTableHeader().setReorderingAllowed(false);  
        jTable1ComponentResized(null);
        jTable3ComponentResized(null);*/
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FGetModel fg = new FGetModel(null, true, 0);
        fg.setVisible(true);
        if(fg.getResult())
        {
            mod = IOModel.getListModel(fg.getResultValue(), 0, true).get(0);
            jTextField1.setText(mod.getArticle());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(mod.getModel()==0)
        {
            JOptionPane.showMessageDialog(null, "Выберите артикул");
            return;
        }
        //System.out.println(new Date());
        jTable1.removeAll();
        
        
        model = new ModelPrognoz1();
        model.setData(IOPrognoz.getDataForPrognoz1(mod.getModel(), jDateChooser2.getDate(), jDateChooser1.getDate(), jDateChooser4.getDate(), yar));
        jTable1.setModel(model);     
        for(int i=0;i<jTable1.getColumnCount();i++)            
        {            
            jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer_center);
            if(i>9)//3            
                if(i<jTable1.getColumnCount()-4)//4                
                    if ((i - 3) % 3 == 0) 
                    {
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer);
                    }
        }
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount()-3).setCellRenderer(jTableRenderer1);
        /*jTable1.getColumnModel().getColumn(0).setCellRenderer(jTableRenderer2);
        jTable1.getColumnModel().getColumn(7).setCellRenderer(jTableRenderer2);
        jTable1.getColumnModel().getColumn(8).setCellRenderer(jTableRenderer2);
        jTable1.getColumnModel().getColumn(9).setCellRenderer(jTableRenderer2);*/
       // gfsdgfsd
        //jTable1ComponentResized(null);  
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    private final DefaultTableCellRenderer jTableRenderer_center = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                           
            cell.setHorizontalAlignment(JLabel.CENTER);
            return cell;
        }

    };
    
    
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FAddColorPlan fc = new FAddColorPlan(null, true, mod.getModel(), jDateChooser3.getDate(), jDateChooser4.getDate(), jDateChooser5.getDate());
        fc.setVisible(true);
        if(fc.getResult())
        {
            FModelPlan m = new FModelPlan(null, true, fc.getPModelPlanInt());
            m.setVisible(true);            
        }
        //model3.setDataModel(mod.getModel(), new Date(), jDateChooser3.getDate());
    }//GEN-LAST:event_jButton4ActionPerformed

    
    
    private void resizeTable()
    {
        //if(1==1) return;
        //System.out.println(jTable1.getColumnCount());
        if(jTable1.getColumnCount()<=0)
            return;
        
        for(int i=0;i<jTable1.getColumnCount();i++)
        {            
            if(i==0)             
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(140);                            
            if(i==7)
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(160);
            if(i==8)
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(120);
            if(i==9)
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(80);
            if(i>0)
            {
                if (i <= 6) 
                {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                    jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                    jTable1.getColumnModel().getColumn(i).setMinWidth(0);
                    //System.out.println("i = " + i);
                }
            }
            
            if(i>9) //3
            {
                if(i>=jTable1.getColumnCount()-4-(model.kol_prognoz*2))    
                {                    
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(80); //40
                    jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer2);
                }
                else
                {
                    if ((i - 3) % 3 == 0) 
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(80);  //40
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer);
                    } else 
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                        jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                        jTable1.getColumnModel().getColumn(i).setMinWidth(0);
                    }
                }
                
            }
            
        }
    }
    
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //model.addLine();
        FAddColorRazmer fr = new FAddColorRazmer(null, true);
        fr.setVisible(true);
        if(fr.getResult())
        {
            model.addLine(fr.getColor(), fr.getRazmeri());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;        
        
        FArticleColorRHistory fa = new FArticleColorRHistory(null, true);
            
        fa.viewData(Integer.valueOf((String)jTable1.getValueAt(h, 1)), Integer.valueOf((String)jTable1.getValueAt(h, 2)), Integer.valueOf((String)jTable1.getValueAt(h, 3)), jDateChooser2.getDate(), jDateChooser1.getDate());
        fa.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //сформировать задачи для производства
        List<PModelPlan> lspm = new ArrayList<>();
        //List<PModelPlanRazmeri> lspmr = new ArrayList<>();
        //List<PModelPlanProduct> lspmp = new ArrayList<>();
        Color c;
        Razmeri r;
        PModelPlan pp;
        PModelPlanRazmeri pr;        
        PModelPlanProduct p1;
        
        PModelYar my;
        String di;
        int kol_qty;
        
        //System.out.println("Max kол-во>" + model.max_kol);
        
        //int i =1;
        //просмотрим все строки таблицы        
        for(List<String> l: model.list)
        {
            if(HelpClass.GetIntIzText(l.get(6))!=0)
                continue;
            
            // если количество больше 0
            if(HelpClass.GetIntIzText(l.get(model.max_kol-2))>0)
            {                
                //сохраним план производства на год
                System.out.println("Кол-во>" + l.get(model.max_kol-2));
                
                c = new Color(HelpClass.GetIntIzText(l.get(4)));
                r = new Razmeri(HelpClass.GetIntIzText(l.get(5)));
                
                my = new PModelYar();
                my.setColor(c);
                my.setModel(mod);
                my.setPmodelyar(0);
                my.setQty(HelpClass.GetIntIzText(l.get(model.max_kol-2)));
                my.setRazmeri(r);
                my.setYar(yar);
                IOPModelYar.savePModelYar(my);
            }               
            
            
            // проверим все строки на задачу
            if(model.kol_prognoz>0)
            {
                //System.out.println("kol str = " + model.kol_prognoz);
                
                
                c = new Color(HelpClass.GetIntIzText(l.get(4)));
                r = new Razmeri(HelpClass.GetIntIzText(l.get(5)));
                
                              
                //просмотрим все задачи
                for(int i=0;i<model.kol_prognoz;i++)
                {
                    //количество нужных изделий
                    kol_qty = HelpClass.GetIntIzText(l.get(model.max_kol + i*2+1));
                    
                    
                    
                    if(kol_qty==0)
                        continue;
                    
                    /*System.out.println("Нужно изделий = " + kol_qty);
                    System.out.println("Цвет = " + c.getName());
                    System.out.println("Размер = " + r.getName());*/
                    
                    //дата когда делаем из таблицы
                    di = HelpClass.getPrintDate4(model.listDatePrognoz.get(i).getD2());
                    //найдем задачу с цветом
                    pp = new PModelPlan(0);
                    for(PModelPlan p: lspm)
                    {                    
                        if(p.getColor().getColor().intValue() == c.getColor().intValue())
                        {                              
                            //если нашли по цвету то ищем по дате когда делаем
                            if(HelpClass.getPrintDate4(p.getDates()).equals(di))
                            {
                                pp = p;
                                break;
                            }
                        }
                    } 
                    //если нет созданной задачи то создадим новую
                    if (pp.getPmodelplan() == 0) 
                    {
                        //System.out.println("Не Нашли");
                        pp = new PModelPlan();
                        pp.setChex(new RabotnikGruppa(0));
                        pp.setColor(c);
                        pp.setDates(model.listDatePrognoz.get(i).getD2());
                        pp.setDates1(model.listDatePrognoz.get(i).getD1());
                        pp.setDates2(new Date());
                        pp.setModel(mod);
                        pp.setStatus(1);
                        pp.setPmodelplan(0);

                        //pp.setPmodelplan(i);
                        //i++;
                        pp.setComment1("");
                        pp.setDates5(model.listDatePrognoz.get(i).getD3());

                        pp = IOModelPlan.setPModelPlan(pp);

                        lspm.add(pp);

                        // сохраним товары которые нужны для заявки
                        for (ModelProduct m : IOModel.getListModelProduct(mod.getModel(), -1, 1)) 
                        {
                            p1 = new PModelPlanProduct();
                            p1.setModelproduct(m);
                            p1.setPmodelplan(pp);
                            p1.setPmodelplanproduct(0);
                            p1.setQty(BigDecimal.ZERO);
                            if (m.getTipproduct().getTipproduct() == 1) {
                                p1.setColor(c);
                            } else {
                                p1.setColor(m.getColor());
                            }
                            p1.setProduct(m.getProduct());
                            IOModelPlan.setPModelPlanProduct(p1);
                        }

                    }
                    // сохраним размер
                    pr = new PModelPlanRazmeri();
                    pr.setPmodelplan(pp);
                    pr.setPmodelplanrazmeri(0);
                    pr.setQty(kol_qty);
                    pr.setTx(l.get(8).substring(l.get(8).indexOf("(") + 1, l.get(8).length() - 1));
                    pr.setRazmeri(r);
                    IOModelPlan.setPModelPlanRazmeri(pr);
                    
                }
            }
                // проверим есть или нет созданная задача
                /*c = new Color(HelpClass.GetIntIzText(l.get(4)));
                r = new Razmeri(HelpClass.GetIntIzText(l.get(5)));
                pp = new PModelPlan(0);
                for(PModelPlan p: lspm)
                {
                    //System.out.println("Цвет ПМ = " + p.getColor().getColor() + " цвет цвета = " + c.getColor());
                    if(p.getColor().getColor().intValue() == c.getColor().intValue())
                    {
                        pp = p;
                        //System.out.println("Нашли");
                        break;
                    }
                }
                //если нет созданной задачи то создадим новую
                if(pp.getPmodelplan()==0)
                {
                    //System.out.println("Не Нашли");
                    pp = new PModelPlan();
                    pp.setChex(new RabotnikGruppa(0));
                    pp.setColor(c);
                    pp.setDates(jDateChooser4.getDate());
                    pp.setDates1(jDateChooser3.getDate());
                    pp.setDates2(new Date());
                    pp.setModel(mod);
                    pp.setStatus(1);
                    pp.setPmodelplan(0);
                    
                    //pp.setPmodelplan(i);
                    //i++;
                    
                    pp.setComment1("");
                    pp.setDates5(jDateChooser5.getDate());
                    
                    pp = IOModelPlan.setPModelPlan(pp);
                    
                    lspm.add(pp);
                    
                    // сохраним товары которые нужны для заявки
                    for (ModelProduct m : IOModel.getListModelProduct(mod.getModel(), -1, 1)) 
                    {
                        p1 = new PModelPlanProduct();
                        p1.setModelproduct(m);
                        p1.setPmodelplan(pp);
                        p1.setPmodelplanproduct(0);
                        p1.setQty(BigDecimal.ZERO);
                        if (m.getTipproduct().getTipproduct() == 1) {
                            p1.setColor(c);
                        } else {
                            p1.setColor(m.getColor());
                        }
                        p1.setProduct(m.getProduct());
                        IOModelPlan.setPModelPlanProduct(p1);
                    }
                    
                }
                // сохраним размер
                pr = new PModelPlanRazmeri();
                pr.setPmodelplan(pp);
                pr.setPmodelplanrazmeri(0);
                pr.setQty(HelpClass.GetIntIzText(l.get(l.size()-2)));
                pr.setTx(l.get(8).substring(l.get(8).indexOf("(")+1,l.get(8).length()-1));
                pr.setRazmeri(r);
                IOModelPlan.setPModelPlanRazmeri(pr);/**/
                

                ////////lspmr.add(IOModelPlan.setPModelPlanRazmeri(pr));
                
                
                
            //}
        }     
        //th.closeTabPage();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        LArticleInArbait la = new LArticleInArbait(null, true, mod.getModel());
        la.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //добавить строки для формирования планирования
        FGetDateMPlan1 f = new FGetDateMPlan1(null, true);
        f.setDates(jDateChooser2.getDate(), jDateChooser1.getDate(), jDateChooser3.getDate(), jDateChooser4.getDate(), jDateChooser5.getDate(), jDateChooser5.getDate());
        f.setDataTemp();
        f.setVisible(true);
        if(f.getResult())
        {
            model.addNewPrognoz(mod.getModel(), f.getDate3(), f.getDate4(), f.getDate5(), f.getDate6(), f.getDate1(), f.getDate2());
            
            
            
            jTable1ComponentResized(null);
            jTable1ComponentResized(null);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        /*int h = jTable1.getSelectedRow();
        if(h==-1) return;
        int c = jTable1.getSelectedColumn();
        c = (int)jTable1.getValueAt(h, c-1);
        if(c==0) return;*/
        List<String> ls = new ArrayList<>();
        FChart1 f = new FChart1(null, true/*, IOAnalitika.getDataForChartForArticleSale(c, jDateChooser1.getDate(), jDateChooser2.getDate())*/, ls, 0, 0, "",false);
        f.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        // TODO add your handling code here:
        resizeTable();
    }//GEN-LAST:event_jTable1ComponentResized

   
    
    
    
    
    
    
    private final DefaultTableCellRenderer jTableRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            //System.out.println("C = " + table.getValueAt(row, column-2));
            
            //String.valueOf(table.getValueAt(row, column-2));
            if(!isSelected)
            {
                int k = Integer.parseInt(String.valueOf(table.getValueAt(row, column-2)));
                if(k<0)
                    cell.setForeground(java.awt.Color.red);
                else
                    cell.setForeground(new java.awt.Color(0, 0, 0));
                
            }
            else
            {
                cell.setText(table.getValueAt(row, column-2) + "/" + cell.getText() + "/" + table.getValueAt(row, column-1));
            }
            cell.setHorizontalAlignment(CENTER);
            
            //System.out.println(table.getValueAt(row, 5));
            
            //if(column>6)
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            
            return cell;
        }

    };
    
    private final DefaultTableCellRenderer jTableRenderer1 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                int k = Integer.parseInt(String.valueOf(table.getValueAt(row, column)));
                //System.out.println(k);
                if(k<0)
                    cell.setForeground(java.awt.Color.red);
                else
                    cell.setForeground(new java.awt.Color(0, 0, 0));
                cell.setHorizontalAlignment(JLabel.CENTER);
                
                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            }
            
            return cell;
        }

    };
    
    private final DefaultTableCellRenderer jTableRenderer2 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            
            return cell;
        }

    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
