/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Analit;

import org.example.Gui.Form.FModel;
import org.example.Gui.Form.Helps.FGetModel;
import org.example.Gui.Plan.LArticleInArbait;
import org.example.Gui.THaupt;
import java.awt.Component;
import java.awt.Dimension;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import static javax.swing.SwingConstants.CENTER;
import javax.swing.table.DefaultTableCellRenderer;
import org.example.logic.Color;
import org.example.logic.Model;
import org.example.logic.ModelProduct;
import org.example.logic.RabotnikGruppa;
import org.example.logic.Razmeri;
import org.example.logic.plan.PModelPlan;
import org.example.logic.plan.PModelPlanHaupt;
import org.example.logic.plan.PModelPlanHauptJournal;
import org.example.logic.plan.PModelPlanProduct;
import org.example.logic.plan.PModelPlanRazmeri;
import org.example.logic.plan.PModelYar;
import org.example.util.HelpClass;
import org.example.util.IOModel;
import org.example.util.analit.IOPrognoz;
import org.example.util.plan.IOModelPlan;
import org.example.util.plan.IOPModelPlanHaupt;
import org.example.util.plan.IOPModelYar;

/**
 *
 * @author ivan
 */  
public class FGetPrognoz1 extends javax.swing.JPanel {

    /**
     * Creates new form FGetPrognoz
     * @param th1
     */
    public FGetPrognoz1(THaupt th1) {
        initComponents();
        th = th1;
        jDateChooser1.setDate(new Date());
        jDateChooser2.setDate(new Date());
        
        jDateChooser2.setDate(new Date(new Long("1499451600000")));
        
        jDateChooser3.setDate(new Date(new Date().getTime() + Long.parseLong("15000000000")));
        
        //jDateChooser3.setVisible(false);
        

        
        lsColor.add(jTableRendererColor0);
        lsColor.add(jTableRendererColor1);
        lsColor.add(jTableRendererColor2);
        lsColor.add(jTableRendererColor3);
        lsColor.add(jTableRendererColor4);
        lsColor.add(jTableRendererColor5);
        lsColor.add(jTableRendererColor6);
        lsColor.add(jTableRendererColor7);
        lsColor.add(jTableRendererColor8);
        lsColor.add(jTableRendererColor9);
        phaupt.setPmodelplanhaupt(0);
        
        
    }
    THaupt th;
    Model mod = new Model(199);
    ModelPrognoz1 model = new ModelPrognoz1();
    PModelPlanHaupt phaupt = new PModelPlanHaupt();
    int yar;
    
    /**
     * Задать параметры
     * @param article - артикул
     * @param d1 - дата с
     * @param d2 - дата по
     * @param d3 - дата закупок
     * @param d4 - дата производства
     * @param d5 - дата начала продаж
     * @param d6 - дата конца продаж
     * @param ya
     */
    public void sendPadamert(int article, Date d1, Date d2, Date d3, Date d4, Date d5, Date d6, int ya)
    {
        yar = ya;
        jTextField2.setText(String.valueOf(ya));
        //System.out.println("art = " + article);
        jDateChooser2.setDate(d1);
        jDateChooser1.setDate(d2);
        jDateChooser3.setDate(d3);
        jDateChooser4.setDate(d4);
        jDateChooser5.setDate(d5);
        jDateChooser6.setDate(d6);
        mod = IOModel.getListModel(article, 0, true).get(0);
        jTextField1.setText(mod.getArticle());   
        jButton3ActionPerformed(null);
        
        System.out.println("art = " + article);
        
    }
    
    List<DefaultTableCellRenderer> lsColor = new ArrayList<>();
    
    //ModelModelPlan  model3 = new ModelModelPlan();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser6 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton8 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jButton1.setText("Закрыть");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jDateChooser1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Дата С");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Дата По");

        jDateChooser2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Артикул");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Показать");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jDateChooser3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Закупки");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Прозводство");

        jDateChooser4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Начало продаж");

        jDateChooser5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField2.setText("2018");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ок. продаж");

        jDateChooser6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(626, 626, 626))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                    .addComponent(jDateChooser6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(510, 510, 510))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 419));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable1.setRowHeight(30);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable1ComponentResized(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setRowHeight(30);
        jTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jTable2ComponentResized(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sun.png"))); // NOI18N
        jButton8.setText("В работе");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/preferences.png"))); // NOI18N
        jButton6.setText("История");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/basket.png"))); // NOI18N
        jButton5.setText("Добавить размер/цвет");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton9.setText("Добавить");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
        jButton7.setText("Сформировать");
        jButton7.setToolTipText("Сформировать задаи для производства");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButton10.setText("График");
        jButton10.setToolTipText("График по продажам выбранного цвета");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/print.png"))); // NOI18N
        jButton11.setText("График 2");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton11);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/catapult.png"))); // NOI18N
        jButton12.setText("График 3");
        jButton12.setFocusable(false);
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton12);

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/timer.png"))); // NOI18N
        jButton4.setText("Пересчет");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/house.png"))); // NOI18N
        jButton13.setText("КК");
        jButton13.setFocusable(false);
        jButton13.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton13);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        th.closeTabPage();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //model.setData();
        //jTable1.setModel(model);
        jButton2.setVisible(false);
        jButton3.setVisible(false);
        
        jTable1.setShowGrid(true);                    
        jTable1.getTableHeader().setReorderingAllowed(false);  
        jTable1.getTableHeader().setPreferredSize(new Dimension(20200, 80));
        
        jTable2.setShowGrid(true);                    
        jTable2.getTableHeader().setReorderingAllowed(false);  
        
        /*jTable3.setShowGrid(true);                    
        jTable3.getTableHeader().setReorderingAllowed(false);  
        jTable1ComponentResized(null);
        jTable3ComponentResized(null);*/
        
    }//GEN-LAST:event_formComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FGetModel fg = new FGetModel(null, true, 0);
        fg.setVisible(true);
        if(fg.getResult())
        {
            mod = IOModel.getListModel(fg.getResultValue(), 0, true).get(0);
            jTextField1.setText(mod.getArticle());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(mod.getModel()==0)
        {
            JOptionPane.showMessageDialog(null, "Выберите артикул");
            return;
        }
        //System.out.println(new Date());
        jTable1.removeAll();
        model = new ModelPrognoz1();
        model.setData(IOPrognoz.getDataForPrognoz1(mod.getModel(), jDateChooser2.getDate(), jDateChooser1.getDate(), jDateChooser4.getDate(), yar));
        jTable1.setModel(model);     
        for(int i=0;i<jTable1.getColumnCount();i++)            
        {            
            jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer_center);
            if(i>9)//3   
            {
                if(i<jTable1.getColumnCount()-4)//4                
                    if ((i - 3) % 3 == 0) 
                    {
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer);
                    }
            }
        }
        jTable1.getColumnModel().getColumn(jTable1.getColumnCount()-3).setCellRenderer(jTableRenderer1);
        
        jTable1.getColumnModel().getColumn(9).setCellRenderer(jTableRenderer2);
         
        jTable2.setModel(model);     
     
        
        jTable2.setSelectionModel(jTable1.getSelectionModel());
        
        jScrollPane2.setRowHeaderView(jTable2);
        jScrollPane2.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTable2.getTableHeader());
        
        
        jTable2.getColumnModel().getColumn(0).setCellRenderer(jTableRenderer2);
        jTable2.getColumnModel().getColumn(7).setCellRenderer(jTableRenderer2);
        jTable2.getColumnModel().getColumn(8).setCellRenderer(jTableRenderer2);
        
        
        
        
        jTable1ComponentResized(null);  
        jTable2ComponentResized(null);  
        
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    
  
    
    
    private final DefaultTableCellRenderer jTableRenderer_center = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);                           
            cell.setHorizontalAlignment(JLabel.CENTER);
            return cell;
        }

    };
    
    
    
    
    private void jTable1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentResized
        // TODO add your handling code here:
        //if(1==1) return;
        //System.out.println(jTable1.getColumnCount());
        if(jTable1.getColumnCount()<=0)
            return;
        
        jTable1.getColumnModel().getColumn(9).setCellRenderer(jTableRenderer2);
        
        for(int i=0;i<jTable1.getColumnCount();i++)
        {            
            if(i==0)    
            {
                //jTable1.getColumnModel().getColumn(i).setPreferredWidth(140);                            
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(i).setMinWidth(0);
            }
            if(i==7)
            {
                //jTable1.getColumnModel().getColumn(i).setPreferredWidth(160);
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(i).setMinWidth(0);
            }
            if(i==8)
            {
                //jTable1.getColumnModel().getColumn(i).setPreferredWidth(120);
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(i).setMinWidth(0);
            }
            if(i==9)
                jTable1.getColumnModel().getColumn(i).setPreferredWidth(80);
            if(i>0)
            {
                if (i <= 6) 
                {
                    jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                    jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                    jTable1.getColumnModel().getColumn(i).setMinWidth(0);
                    //System.out.println("i = " + i);
                }
            }
            
            if(i>9) //3
            {
                //if(i>=jTable1.getColumnCount()-4-(model.kol_prognoz*2))    
                if(i>=jTable1.getColumnCount()-5-(model.kol_prognoz*2))    
                {                    
                    //if(i==jTable1.getColumnCount()-4-(model.kol_prognoz*2))
                    if(i==jTable1.getColumnCount()-5-(model.kol_prognoz*2))
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(100); //40
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer2);
                    }
                    else
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(80); //40
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer2);
                    }
                }
                else
                {
                    if ((i - 3) % 3 == 0) 
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(80);  //40
                        jTable1.getColumnModel().getColumn(i).setCellRenderer(jTableRenderer);
                    } else 
                    {
                        jTable1.getColumnModel().getColumn(i).setPreferredWidth(0);
                        jTable1.getColumnModel().getColumn(i).setMaxWidth(0);
                        jTable1.getColumnModel().getColumn(i).setMinWidth(0);
                    }
                }
                
            }
            
        }
        if(model.kol_prognoz>0)
        {            
            for(int y=0;y<model.kol_prognoz;y++)
            {                
                if(y<10)
                {
                    jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-2-((model.kol_prognoz-y)*2)).setCellRenderer(lsColor.get(y));                
                    jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-1-((model.kol_prognoz-y)*2)).setCellRenderer(lsColor.get(y));                
                    //jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-2-((model.kol_prognoz-y)*2)).setHeaderRenderer(lsColor.get(y));                
                    //jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-1-((model.kol_prognoz-y)*2)).setHeaderRenderer(lsColor.get(y));                
                }
                else
                {
                    jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-2-((model.kol_prognoz-y)*2)).setCellRenderer(lsColor.get(y%10));                
                    jTable1.getColumnModel().getColumn(jTable1.getColumnModel().getColumnCount()-1-((model.kol_prognoz-y)*2)).setCellRenderer(lsColor.get(y%10));                
                }
            }
                    
        }
    }//GEN-LAST:event_jTable1ComponentResized

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //model.addLine();
        FAddColorRazmer fr = new FAddColorRazmer(null, true);
        fr.setVisible(true);
        if(fr.getResult())
        {
            model.addLine(fr.getColor(), fr.getRazmeri());
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;        
        
        FArticleColorRHistory fa = new FArticleColorRHistory(null, true);
            
        fa.viewData(Integer.valueOf((String)jTable1.getValueAt(h, 1)), Integer.valueOf((String)jTable1.getValueAt(h, 2)), Integer.valueOf((String)jTable1.getValueAt(h, 3)), jDateChooser2.getDate(), jDateChooser1.getDate());
        fa.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        
        //если создаем новую задачу
        if(phaupt.getPmodelplanhaupt()==0)
        {
            phaupt.setDates(new Date());
            phaupt.setDates1(jDateChooser2.getDate());
            phaupt.setDates2(jDateChooser1.getDate());
            phaupt.setDates3(jDateChooser3.getDate());
            phaupt.setDates4(jDateChooser4.getDate());
            phaupt.setDates5(jDateChooser5.getDate());
            phaupt.setDates6(jDateChooser6.getDate());
            phaupt.setModel(mod);
            phaupt = IOPModelPlanHaupt.setPModelPlanHaupt(phaupt);            
        }
        
        //сформировать задачи для производства
        List<PModelPlan> lspm = new ArrayList<>();
        //List<PModelPlanRazmeri> lspmr = new ArrayList<>();
        //List<PModelPlanProduct> lspmp = new ArrayList<>();
        Color c;
        Razmeri r;
        PModelPlan pp;
        PModelPlanRazmeri pr;        
        PModelPlanProduct p1;
        
        PModelYar my;
        String di;
        int kol_qty;
        
        PModelPlan p12;
        //Загрцзим созданные задачи
        if(model.kol_prognoz>0)
        {
            for(datePrognoz p: model.listDatePrognoz)
            {
                if(p.getPmodel()>0)
                {     
                    p12 = IOModelPlan.getPModelPlan(p.getPmodel());
                    lspm.add(p12);
                    //ели можно редактировать то удалим размеры
                    if(p12.getStatus()<2)                     
                    {                        
                        IOModelPlan.delModelPlanRarmeriForMP(p.getPmodel());
                    }
                    //System.out.println("Удалим = " + p.getPmodel());
                }
            }
        }
        
        //System.out.println("Max kол-во>" + model.max_kol);
        
        //int i =1;
        //просмотрим все строки таблицы        
        for(List<String> l: model.list)
        {
            if(HelpClass.GetIntIzText(l.get(6))!=0)
                continue;
            
            // если количество больше 0
            if(HelpClass.GetIntIzText(l.get(l.size()-1))>0)
            {                
                //сохраним план производства на год
                //System.out.println("Кол-во>" + l.get(model.max_kol-2));
                
                c = new Color(HelpClass.GetIntIzText(l.get(4)));
                r = new Razmeri(HelpClass.GetIntIzText(l.get(5)));
                
                my = new PModelYar();
                my.setColor(c);
                my.setModel(mod);
                my.setPmodelyar(0);
                my.setQty(HelpClass.GetIntIzText(l.get(l.size()-1)));
                my.setRazmeri(r);
                my.setYar(yar);
                IOPModelYar.savePModelYar(my);
            }               
            
            
            // проверим все строки на задачу
            if(model.kol_prognoz>0)
            {
                //System.out.println("kol str = " + model.kol_prognoz);
                
                
                c = new Color(HelpClass.GetIntIzText(l.get(4)));
                r = new Razmeri(HelpClass.GetIntIzText(l.get(5)));
                
                              
                //просмотрим все задачи
                for(int i=0;i<model.kol_prognoz;i++)
                {
                    //если нельзя редактировать то пропустим
                    //if(!model.listDatePrognoz.get(i).isIsRead())
                    //    continue;
                    //количество нужных изделий
                    //kol_qty = HelpClass.GetIntIzText(l.get(model.max_kol + i*2+1));
                    kol_qty = HelpClass.GetIntIzText(l.get(model.max_kol - 2 + i*2+1));
                    
                    
                    
                    if(kol_qty==0)
                        continue;
                    
                    /*System.out.println("Нужно изделий = " + kol_qty);
                    System.out.println("Цвет = " + c.getName());
                    System.out.println("Размер = " + r.getName());*/
                    
                    //дата когда делаем из таблицы
                    di = HelpClass.getPrintDate4(model.listDatePrognoz.get(i).getD2());
                    //найдем задачу с цветом
                    pp = new PModelPlan(0);
                    for(PModelPlan p: lspm)
                    {                    
                        if(p.getColor().getColor().intValue() == c.getColor().intValue())
                        {                              
                            //если нашли по цвету то ищем по дате когда делаем
                            if(HelpClass.getPrintDate4(p.getDates()).equals(di))
                            {
                                pp = p;
                                break;
                            }
                        }
                    } 
                    //если нет созданной задачи то создадим новую
                    if (pp.getPmodelplan() == 0) 
                    {
                        System.out.println("Не Нашли");
                        pp = new PModelPlan();
                        pp.setChex(new RabotnikGruppa(0));
                        pp.setColor(c);
                        pp.setDates(model.listDatePrognoz.get(i).getD2());
                        pp.setDates1(model.listDatePrognoz.get(i).getD1());
                        pp.setDates2(new Date());
                        pp.setDates6(model.listDatePrognoz.get(i).getD6());
                        pp.setDates7(model.listDatePrognoz.get(i).getD4());
                        pp.setDates8(model.listDatePrognoz.get(i).getD5());
                        pp.setModel(mod);
                        pp.setStatus(1);
                        pp.setPmodelplan(0);

                        //pp.setPmodelplan(i);
                        //i++;
                        pp.setComment1("");
                        pp.setDates5(model.listDatePrognoz.get(i).getD3());

                        pp = IOModelPlan.setPModelPlan(pp);

                        lspm.add(pp);

                        // сохраним товары которые нужны для заявки
                        for (ModelProduct m : IOModel.getListModelProduct(mod.getModel(), -1, 1)) 
                        {
                            p1 = new PModelPlanProduct();
                            p1.setModelproduct(m);
                            p1.setPmodelplan(pp);
                            p1.setPmodelplanproduct(0);
                            p1.setQty(BigDecimal.ZERO);
                            if (m.getTipproduct().getTipproduct() == 1) {
                                p1.setColor(c);
                            } else {
                                p1.setColor(m.getColor());
                            }
                            p1.setProduct(m.getProduct());
                            IOModelPlan.setPModelPlanProduct(p1);
                        }

                    }
                    // сохраним размер
                    pr = new PModelPlanRazmeri();
                    pr.setPmodelplan(pp);
                    pr.setPmodelplanrazmeri(0);
                    pr.setQty(kol_qty);
                    //System.out.println(">> " + l.get(8).substring(l.get(8).indexOf("(") + 1, l.get(8).length() - 1));
                    pr.setTx(l.get(8).substring(l.get(8).indexOf("(") + 1, l.get(8).length() - 1));
                    pr.setRazmeri(r);
                    if(pp.getStatus()<2)
                        IOModelPlan.savePModelPlanRazmeri(pr);                    
                }
            }
                
        }     
        // сохраним все задачи для заголовка задач
        PModelPlanHauptJournal j;
        for(PModelPlan p: lspm)
        {
            j = new PModelPlanHauptJournal();
            j.setPmodelplan(p);
            j.setPmodelplanhaupt(phaupt);
            j.setPmodelplanhauptjournal(0);
            IOPModelPlanHaupt.savePModelPlanHauptJournal(j);
        }
        th.closeTabPage();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        LArticleInArbait la = new LArticleInArbait(null, true, mod.getModel());
        la.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        //добавить строки для формирования планирования
        FGetDateMPlan1 f = new FGetDateMPlan1(null, true);
        f.setDates(jDateChooser2.getDate(), jDateChooser1.getDate(), jDateChooser3.getDate(), jDateChooser4.getDate(), jDateChooser5.getDate(), jDateChooser6.getDate());
        f.setDataTemp();
        f.setVisible(true);
        if(f.getResult())
        {
            model.addNewPrognoz(mod.getModel(), f.getDate3(), f.getDate4(), f.getDate5(), f.getDate6(),  f.getDate1(), f.getDate2());         
                      
            jTable1ComponentResized(null);
            jTable1ComponentResized(null);
            
            jTable2ComponentResized(null);
            jTable2ComponentResized(null);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        
        FChart1 f = new FChart1(null, true, IOPrognoz.getQtySaleForChar(Integer.valueOf((String)jTable1.getValueAt(h, 1)), Integer.valueOf((String)jTable1.getValueAt(h, 2)), jDateChooser2.getDate(), jDateChooser1.getDate()), getWidth()-50, getHeight()-50, "Артикул:"+(String)jTable1.getValueAt(h, 0) + " Цвет:"+(String)jTable1.getValueAt(h, 7), true);
        f.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTable2ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable2ComponentResized
        // TODO add your handling code here:
        if(jTable2.getColumnCount()<=0)
            return;
        jTable2.getColumnModel().getColumn(0).setCellRenderer(jTableRenderer2);
        jTable2.getColumnModel().getColumn(7).setCellRenderer(jTableRenderer2);
        jTable2.getColumnModel().getColumn(8).setCellRenderer(jTableRenderer2);
        
        for(int i=0;i<jTable2.getColumnCount();i++)
        {            
            if(i==0)             
                jTable2.getColumnModel().getColumn(i).setPreferredWidth(140);                            
            if(i==7)
                jTable2.getColumnModel().getColumn(i).setPreferredWidth(160);
            if(i==8)
                jTable2.getColumnModel().getColumn(i).setPreferredWidth(120);            
            if(i>0)
            {
                if (i <= 6) 
                {
                    jTable2.getColumnModel().getColumn(i).setPreferredWidth(0);
                    jTable2.getColumnModel().getColumn(i).setMaxWidth(0);
                    jTable2.getColumnModel().getColumn(i).setMinWidth(0);
                    //System.out.println("i = " + i);
                }
            }
            
            if(i>=9) //3
            {
                jTable2.getColumnModel().getColumn(i).setPreferredWidth(0);
                jTable2.getColumnModel().getColumn(i).setMaxWidth(0);
                jTable2.getColumnModel().getColumn(i).setMinWidth(0);
                
                
            }
            
            
        }       
        
                    
    }//GEN-LAST:event_jTable2ComponentResized

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        if(h==-1) return;
        //System.out.println("Артикул:"+(String)jTable1.getValueAt(h, 0) + " Цвет:"+(String)jTable1.getValueAt(h, 7));
        FChart1 f = new FChart1(null, true, IOPrognoz.getQtySaleForChar1(Integer.valueOf((String)jTable1.getValueAt(h, 1)), jDateChooser2.getDate(), jDateChooser1.getDate()), getWidth()-50, getHeight()-50, "Артикул:"+(String)jTable1.getValueAt(h, 0), true );
        f.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedColumn();
        if(h==-1) return;
        
        if(h<model.max_kol-2)
            return;
        if(h>jTable1.getColumnCount()-3)
            return;
        
        h = -(model.max_kol-2-h);
        h = h - h%2;
        h = h/2;
        
        //System.out.println("Index = " + h);
        datePrognoz dp =  model.listDatePrognoz.get(h);
                
        FGetDateMPlan1 f = new FGetDateMPlan1(null, true);
        f.setDates(dp.getD4(), dp.getD5(), dp.getD1(), dp.getD2(), dp.getD3(), dp.getD6());
        f.setDataTemp2();
        f.setVisible(true);
        if(f.getResult())
        {
            dp.setD4(f.getDate1());
            dp.setD5(f.getDate2());
            model.listDatePrognoz.set(h, dp);
            model.repriceCol(h, f.getDate1(), f.getDate2());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int h = jTable1.getSelectedRow();
        //if(h==-1) return;
        System.out.println("mod>" + mod.getModel());
        System.out.println("col>" + Integer.valueOf((String)jTable1.getValueAt(h, 4)));
        System.out.println("raz>" + Integer.valueOf((String)jTable1.getValueAt(h, 5)));
        
        FChart2 f = new FChart2(null, true, IOPrognoz.getQtySaleForChar2(Integer.valueOf((String)jTable1.getValueAt(h, 1)), jDateChooser2.getDate(), jDateChooser1.getDate()), getWidth()-50, getHeight(), "Артикул:"+(String)jTable1.getValueAt(h, 0) + " Цвет:"+(String)jTable1.getValueAt(h, 7), true, Integer.valueOf((String)jTable1.getValueAt(h, 1)), Integer.valueOf((String)jTable1.getValueAt(h, 2)), jDateChooser2.getDate(), jDateChooser1.getDate());
        f.setVisible(true);
        
        if(f.getResult())
        {
            model.addNewPrognoz(mod.getModel(), f.getDate3(), f.getDate4(), f.getDate5(), f.getDate6(),  f.getDate1(), f.getDate2());         
                      
            jTable1ComponentResized(null);
            jTable1ComponentResized(null);
            
            jTable2ComponentResized(null);
            jTable2ComponentResized(null);            
        }
        
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        FModel fm = new FModel(null, true, mod.getModel(), getWidth(), getHeight());
        fm.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

   
    
    
    
    
    
    
    private final DefaultTableCellRenderer jTableRenderer = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            //System.out.println("C = " + table.getValueAt(row, column-2));
            
            //String.valueOf(table.getValueAt(row, column-2));
            if(!isSelected)
            {
                int k = Integer.parseInt(String.valueOf(table.getValueAt(row, column-2)));
                if(k<0)
                    cell.setForeground(java.awt.Color.red);
                else
                    cell.setForeground(new java.awt.Color(0, 0, 0));
                
            }
            else
            {
                cell.setText(table.getValueAt(row, column-2) + "/" + cell.getText() + "/" + table.getValueAt(row, column-1));
            }
            cell.setHorizontalAlignment(CENTER);
            
            //System.out.println(table.getValueAt(row, 5));
            
            //if(column>6)
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            
            return cell;
        }

    };
    
    private final DefaultTableCellRenderer jTableRenderer1 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                int k = Integer.parseInt(String.valueOf(table.getValueAt(row, column)));
                //System.out.println(k);
                if(k<0)
                    cell.setForeground(java.awt.Color.red);
                else
                    cell.setForeground(new java.awt.Color(0, 0, 0));
                cell.setHorizontalAlignment(JLabel.CENTER);
                
                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            }
            
            return cell;
        }

    };
    
     private final DefaultTableCellRenderer jTableRendererColor1 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(1));                
                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(1));                
                
                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor2 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(2));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(2));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor3 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(3));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(3));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor4 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(4));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(4));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
      private final DefaultTableCellRenderer jTableRendererColor5 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(5));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(5));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor6 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(6));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(6));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor7 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(7));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(7));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor8 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(8));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(8));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
      private final DefaultTableCellRenderer jTableRendererColor9 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(9));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(9));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
     private final DefaultTableCellRenderer jTableRendererColor0 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if(!isSelected)
            {
                //cell.setForeground(model.lsColor.get(0));                
                cell.setOpaque(true);
                cell.setBackground(model.lsColor.get(0));                
                cell.setHorizontalAlignment(JLabel.CENTER);
                //model.max_kol
                //cell.setToolTipText(cell.getText() + "jgfdklghsldkfjghjkldf");
                                
                if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                    cell.setFont(new java.awt.Font("Tahoma", 1, 14)); 
            }
            
            return cell;
        }

    };
     
    
     
     
     
    
    private final DefaultTableCellRenderer jTableRenderer2 = new DefaultTableCellRenderer() {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {

            JLabel cell = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            cell.setHorizontalAlignment(CENTER);
            if(Integer.parseInt((String)table.getValueAt(row, 6))==1)
                cell.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            
            return cell;
        }

    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private com.toedter.calendar.JDateChooser jDateChooser6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    /**
     * Показать прогноз 
     * @param pm1 - номер задачи  
     */
    public void loadModelPlan(int pm1)
    {
        PModelPlan pm = IOModelPlan.getPModelPlan(pm1);

        //jButton5.setVisible(false);
        //jButton9.setVisible(false);
        model.addNewPrognoz1(mod.getModel(), pm.getDates1(), pm.getDates(), pm.getDates5(), pm.getDates6(),  jDateChooser2.getDate(), jDateChooser1.getDate(), pm.getPmodelplan(), pm.getColor().getColor(), !(pm.getStatus()>1));         
        jTable1ComponentResized(null);
        jTable1ComponentResized(null);
            
        jTable2ComponentResized(null);
        jTable2ComponentResized(null);
    }
    
    /**
     * Показать прогноз 
     * @param pm1 - номер задачи  
     */
    public void loadModelPlanHaupt(int pm1)
    {
        //PModelPlan pm = IOModelPlan.getPModelPlan(pm1);

        phaupt = IOPModelPlanHaupt.getPModelPlanHaupt(pm1);
        //jButton5.setVisible(false);
        //jButton9.setVisible(false);
        //model.addNewPrognoz1(mod.getModel(), pm.getDates1(), pm.getDates(), pm.getDates5(), pm.getDates6(),  jDateChooser2.getDate(), jDateChooser1.getDate(), pm.getPmodelplan(), pm.getColor().getColor());         
        model.loadPrognoz(pm1);
        jTable1ComponentResized(null);
        jTable1ComponentResized(null);
            
        jTable2ComponentResized(null);
        jTable2ComponentResized(null);
    }
}
