/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.example.Gui.Analit;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.block.BlockBorder;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.RectangleInsets;

/**
 *
 * @author ivan
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }
    
    public void setDate(List<String> ls1, int w1, int h1, String tTitle1, boolean renameMont1)
    {
        ls = ls1;
        w = w1;
        h = h1;
        tTitle = tTitle1;
        renameMont = renameMont1;  
        
    }
    
    List<String> ls;
    String tTitle;
    int w,h;
    boolean renameMont = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 398, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        createDemoPanel();
        repaint();
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

     private JFreeChart createChart(CategoryDataset dataset) 
    {
        JFreeChart chart = ChartFactory.createBarChart(
                "Продажи за период",
                null, // x-axis label
                "Кол-во", // y-axis label
                dataset);
        chart.addSubtitle(new TextTitle(tTitle));
        chart.setBackgroundPaint(Color.white);

        CategoryPlot plot = (CategoryPlot) chart.getPlot();
        
        
        
        CategoryAxis axis = plot.getDomainAxis();
        axis.setCategoryLabelPositions(CategoryLabelPositions.UP_90);
        

        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setDrawBarOutline(false);
        chart.getLegend().setFrame(BlockBorder.NONE);

        return chart;
    }
    
    
    
private CategoryDataset createDataset()
{
    DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    String ss[];
    for(String s: ls)
    {
        ss = s.split("<!>");
        if(renameMont)
            dataset.addValue(Integer.parseInt(ss[0]), ss[1] , renameMontStr(ss[2]));
        else
            dataset.addValue(Integer.parseInt(ss[0]), ss[1] , ss[2]);
    }
    
 
    return dataset;
}
  

private String renameMontStr(String str)
{
    if(str.length()<6)
        return str;
    String s = str.substring(4,6);
    if(s.substring(0,1).equals("0"))
        s = s.substring(1,2);
    
    List<String> ls1 = new ArrayList<>();
    ls1.add("Январь");
    ls1.add("Февраль");
    ls1.add("Март");
    ls1.add("Апрель");
    ls1.add("Май");
    ls1.add("Июнь");
    ls1.add("Июль");
    ls1.add("Август");
    ls1.add("Сентябрь");
    ls1.add("Октябрь");
    ls1.add("Ноябрь");
    ls1.add("Декабрь");
    
    
    return str.substring(0,4) + " " + ls1.get(Integer.parseInt(s)-1);
}

    
JPanel jp = new JPanel();
public JPanel createDemoPanel()
{
    JFreeChart chart = createChart(createDataset());
    chart.setPadding(new RectangleInsets(4, 8, 2, 2));    
    
    
    
    
    ChartPanel panel = new ChartPanel(chart);
    panel.setDomainZoomable(true);
    //panel.setFillZoomRectangle(true);
    panel.setMouseWheelEnabled(true);
    panel.setPreferredSize(new Dimension(getWidth(), getHeight()-150));
    
    //jp.setBounds(100, 100, getWidth(), getHeight()-150);
    //jp.setPreferredSize(new Dimension(getWidth(), getHeight()-150));
    //jp.add(panel, BorderLayout.CENTER);
    
    
    //this.setLayout(null);
    //this.add(jp);
    
    
    //jPanel2.add(panel, BorderLayout.CENTER);
    //jPanel2.validate();
    
    //jPanel1.add(jp);
    
    
    this.add(panel);
    //setContentPane(panel);
    
    /*Container c = getContentPane();
    c.add(jp);
    setContentPane(c);*/
    
    
    
    
    //setContentPane(jButton1);
    
    
    return panel;
}
}


